spring.application.name=user-service
server.port=8081

spring.config.import=optional:configserver:http://localhost:8888

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:postgresql://localhost:5432/leave_management_system
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET:Q3Jlc2VuTGVhdmVNYW5hZ2VtZW50U3lzdGVtSldUU2VjcmV0S2V5Rm9ySFMyNTY=}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

security.otp.expiration-minutes=${OTP_EXPIRATION_MINUTES:10}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=viveksinhchavda@gmail.com
spring.mail.password=drauzuufuzlddfwy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=viveksinhchavda@gmail.com

management.endpoints.web.exposure.include=health,info
